name: BUILD

on:
  schedule:
    - cron: "1 */8 * * *"
  workflow_dispatch:

jobs:
  # 读取 PKGLIST 文件并转换成 JSON 给下一步读取
  pkglist:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.parse.outputs.pkglist }}
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "pkglist.yaml"
          from: "yaml"
          to: "json"
      - uses: ./parse-pkglist
        id: parse
        with:
          pkglist: ${{ steps.yaml2json.outputs.data }}

  buildAUR-pack:
    runs-on: ubuntu-latest
    needs:
      - pkglist
    strategy:
      matrix:
        include: ${{ fromJSON(needs.pkglist.outputs.data).builds-on-x86_64 }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v1

      - name: 检查包是否已存在
        id: is-needed
        uses: ./check-is-needed
        with:
          package-name: ${{ matrix.repo }}
          arch: ${{ matrix.arch }}

      - name: 使用 yay 构建包
        id: build
        uses: Misaka13514-AUR/build-aur-action@main
        if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
        with:
          repo-name: ${{ matrix.repo }}
          arch: ${{ matrix.arch }}

      - name: 同步 docker 内外目录
        # $PWD 在 docker 中被映射到 /github/workspace
        if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
        run: |
          sudo mkdir /github
          sudo ln -s $PWD /github/workspace

      - name: 复制文件以便上传
        # rclone 没法指定多个文件
        if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
        run: |
          mkdir rclone-upload
          cp ${{ steps.build.outputs.filelist }} rclone-upload/

      - uses: NiceLabs/rclone-action@master
        if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          config: ${{ secrets.RCLONE_CONF }}
          config-secret-name: RCLONE_CONF

      - name: 把包使用 rclone 上传
        if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
        run: rclone copy rclone-upload/ ${{ secrets.REPO_PATH }}/
